// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    APagination: typeof import('ant-design-vue/es')['Pagination']
    NoToken: typeof import('./src/components/shared/NoToken.vue')['default']
    VanEmpty: typeof import('vant/es')['Empty']
  }
}

export { }
